name: Preview Deploy

on:
  pull_request:
    branches: [main, master, develop]
    types: [opened, synchronize, reopened]

jobs:
  preview-deploy:
    name: Deploy Preview
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install functions dependencies
        run: npm ci --prefix functions

      - name: Install web dependencies
        run: npm ci --prefix web

      - name: Build functions
        run: npm run build:functions

      - name: Build web
        run: npm run build:web

      - name: Generate preview URL
        id: preview
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          PREVIEW_URL="https://preview-pr-${PR_NUMBER}.plzfixthx.dev"
          echo "preview_url=${PREVIEW_URL}" >> $GITHUB_OUTPUT
          echo "Preview URL: ${PREVIEW_URL}"

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = '${{ steps.preview.outputs.preview_url }}';
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 Preview deployment ready!\n\n[View Preview](${previewUrl})\n\n**Build Info:**\n- Commit: ${context.sha.substring(0, 7)}\n- Branch: ${context.ref}`
            });

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: preview-build-${{ github.event.pull_request.number }}
          path: |
            web/dist
            functions/lib
          retention-days: 7

